-- PostgreSQL table for the validated processed employee dataset.
CREATE TABLE IF NOT EXISTS public.employee_analytics (
    age INTEGER NOT NULL CHECK (age BETWEEN 18 AND 60),
    attrition BOOLEAN NOT NULL,
    business_travel TEXT NOT NULL,
    daily_rate INTEGER NOT NULL CHECK (daily_rate >= 0),
    department TEXT NOT NULL,
    distance_from_home INTEGER NOT NULL CHECK (distance_from_home >= 0),
    education INTEGER NOT NULL CHECK (education BETWEEN 1 AND 5),
    education_field TEXT NOT NULL,
    employee_id INTEGER PRIMARY KEY,
    environment_satisfaction INTEGER NOT NULL CHECK (environment_satisfaction BETWEEN 1 AND 4),
    gender TEXT NOT NULL,
    hourly_rate INTEGER NOT NULL CHECK (hourly_rate >= 0),
    job_involvement INTEGER NOT NULL CHECK (job_involvement BETWEEN 1 AND 4),
    job_level INTEGER NOT NULL CHECK (job_level BETWEEN 1 AND 5),
    job_role TEXT NOT NULL,
    job_satisfaction INTEGER NOT NULL CHECK (job_satisfaction BETWEEN 1 AND 4),
    marital_status TEXT NOT NULL,
    monthly_income INTEGER NOT NULL CHECK (monthly_income >= 0),
    monthly_rate INTEGER NOT NULL CHECK (monthly_rate >= 0),
    num_companies_worked INTEGER NOT NULL CHECK (num_companies_worked >= 0),
    over_time BOOLEAN NOT NULL,
    percent_salary_hike INTEGER NOT NULL CHECK (percent_salary_hike >= 0),
    performance_rating INTEGER NOT NULL CHECK (performance_rating BETWEEN 3 AND 4),
    relationship_satisfaction INTEGER NOT NULL CHECK (relationship_satisfaction BETWEEN 1 AND 4),
    stock_option_level INTEGER NOT NULL CHECK (stock_option_level BETWEEN 0 AND 3),
    total_working_years INTEGER NOT NULL CHECK (total_working_years >= 0),
    training_times_last_year INTEGER NOT NULL CHECK (training_times_last_year >= 0),
    work_life_balance INTEGER NOT NULL CHECK (work_life_balance BETWEEN 1 AND 4),
    years_at_company INTEGER NOT NULL CHECK (years_at_company >= 0),
    years_in_current_role INTEGER NOT NULL CHECK (years_in_current_role >= 0),
    years_since_last_promotion INTEGER NOT NULL CHECK (years_since_last_promotion >= 0),
    years_with_curr_manager INTEGER NOT NULL CHECK (years_with_curr_manager >= 0),
    age_group TEXT NOT NULL,
    tenure_group TEXT NOT NULL,
    income_band TEXT NOT NULL,
    CHECK (years_at_company <= total_working_years),
    CHECK (years_in_current_role <= years_at_company),
    CHECK (years_with_curr_manager <= years_at_company)
);
